### ISSUE TITLE
[Feature Request] Customize Actor Object Field Values

### ISSUE THREAD

**Issue by DeadSuperHero** [jdormit/pterotype#1]
**The Situation**
Currently, the Pterotype plugin leverages the `Site Title` for an AP Actor's Display Name, and `Tagline` for the profile description. Overall this works pretty well, and the mapping largely makes sense for accounts representing a publication. At the very least, this is a pretty sane default for a plugin that does not require any configuration.

![social_nasqueron](https://user-images.githubusercontent.com/401560/47536943-d02b3300-d877-11e8-9e72-6d6b38ceae68.png)

Overall, this is a pretty good approach, but it would be really nice for this integration to let WP Site admins specify how field values get returned. For example, currently this plugin doesn't return an avatar for `blog@staging.wedistribute.org`, and there isn't any way to set one.

**The Proposal**
It would be nice if the blog@ Actor allowed a Wordpress Admin to update the following values:
* Avatar
* Display Name
* Description

If the plugin configuration page does not include values in those fields, Pterotype could instead fall back to using `Site Title` and `Tagline` for Display Name and Description values on the Actor object.

**Comment by jdormit** [comment]
I agree, and this is on the roadmap. Another related problem to fix is that
Pterotype doesn't currently post Update activities for the Actor objects
when these fields change, which means that updates to site title etc. won't
be reflected in federated systems that keep a local copy of the object -
so, e.g. the blog's Mastodon profile page won't get updated with the new
information.

**Comment by DeadSuperHero** [comment]
Ah, good to know! 😀

**Comment by jdormit** [comment]
I'll put together some sort of roadmap document to publicize what I'm
thinking and how I'm prioritizing stuff.

Thanks for taking the time to give feedback, by the way 😊

**Comment by jdormit** [comment]
Okay, I released the development roadmap [here](https://getpterotype.com/roadmap/).

**Comment by DeadSuperHero** [comment]
I can confirm that this now works! Basically all one has to do is go to Customize on their Wordpress site, and set the Site Logo.

![social_nasqueron](https://user-images.githubusercontent.com/401560/47932272-6d94f100-de8e-11e8-93ee-364046207859.png)

All in all, this is very good news!

**Comment by jdormit** [comment]
Release 1.2.6 added an admin menu where the site's icon, description, and name in the Fediverse can be customized separately from the WordPress site identity. This means that you don't need to set your site logo to set the Fediverse logo, etc. 

Customizing the username (@blog@thesite.com) is a little more complicated since we need to ensure that WebFinger requests for the old username still succeed so as not to break existing @mentions to the blog. I'm going to close this issue since the initial request of avatar, site name, and description has been implemented, but my next goal is making the username configurable as well.
