### ISSUE TITLE
Broadening out: Pterotype - Feed your content to the Fediverse

### ISSUE THREAD

**Issue by aschrijver** [jdormit/pterotype#3]
Hi @jdormit ,

Great project you got going here. I just found out about it, and love the idea. But there is one thing I was wondering about.. Aren't you selling this idea short, by positioning like this:

> **A WordPress plugin** that expands your audience by giving your site an ActivityPub stream

Why not position the project like your statement further on:

> Pterotype connects your blog to the Fediverse by giving it an ActivityPub feed.

And then not just for blogs, but for content in general, positioning something like:

- Pterotype: Library that expands your audience to the Fediverse through ActivityPub content streams
  - Very easy to set up, just choose the appropriate connector for you: WordPress, Jekyll, Gatsby, ...
  - Create your own connector for your platform with comprehensive SDK, see documentation here ...

You'll just keep doing what you were before, creating a WordPress plugin, but with the project and codebase structured such that additional connectors become easy to add, and with more focus on the specification, documentation and API of the 'Fediverse connector' (which is not a bad thing, as with most AP projects the specs + docs are usually mostly 'hidden in the code').

**Comment by jdormit** [comment]
Thanks for the encouraging words! A few thoughts on this:

> with the project and codebase structured such that additional connectors become easy to add

This wouldn't be possible with this code base. It's tightly coupled with the way WordPress does things, uses WordPress-specific functions and classes, etc.

In general, I like the idea of building out a more generic ActivityPub connector for sites. I've thought about building out AP integrations for Hugo or Jekyll, although that's inherently problematic since ActivityPub requires dynamic responses from the server to respond to e.g. WebMentions, which makes it difficult to see how to build something for a static site generator.

My ultimate mission is to put the whole web into the Fediverse. I started with WordPress because WordPress runs 30% of the internet. But I don't think the way to do that is with some sort of generic library/SDK - I'm not sure such a thing is even possible, given how different every web content platform is. So I'm going to start with Pterotype (the WordPress plugin) and use it to build up interest in the Fediverse, to add lots of content to the Fediverse, and to learn what I can about designing federated software.

At some point in the future I will want to expand that - I've been thinking about ActivityPub clients that let you view/read/organize federated content in novel ways; ActivityPub-powered apps for businesses like federated wikis or bug trackers; even analytics and advanced marketing tools for ActivityPub services (nothing shady or privacy-invasive, though). Basically, I'm not sure what's next after Pterotype, and I don't want to commit to anything until I've seen this project out. There's still a lot we can do for the Fediverse with a WordPress plugin before we need to think bigger.

**Comment by aschrijver** [comment]
Thank you. Yes, I understand your reasoning. Note, that I didn't take (nor have) the time to figure out how you implemented the project. But I am working on Jekyll and Gatsby side-projects myself, and was thinking of having the sites publish updates to an existing account on e.g. a Mastodon server, and - when a user clicks the feed icon - show a rendering of the feed from the account in a site-branded layout. Thus the functionality would not be an AP server, and have to respond to mentions.

Regarding AP in general I have plans - if there is interest in OSS community - to start a GPL-licensed AP project named Outreach™ to help communities reinforce their message via social media channels. The community I am part of ([Humane Tech Community](https://community.humanetech.com)) would use that for our Awareness Campaigns project.

**Comment by jdormit** [comment]
Having the static site generate use a client to an existing AP server is a good idea - that'll definitely simplify the integration. Best of luck with Outreach! The Fediverse needs more organizations pushful useful products built on top of it - it's the only way it'll achieve the critical mass and userbase to take off.

I'm going to close out this issue now, but feel free to reach out on Mastodon to continue the discussion.
